using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.1.3.0")]
[assembly: AssemblyTitleAttribute("MPS.MPP.Auxiliary.ConaxWorkflowManager")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2015, MPS Broadband AB.")]
[assembly: AssemblyConfigurationAttribute("Debug")]
[assembly: AssemblyCompanyAttribute("MPS Broadband")]
[assembly: AssemblyProductAttribute("MPS.MPP.Auxiliary.ConaxWorkflowManager")]
[assembly: AssemblyTrademarkAttribute("MPS.MPP.Auxiliary.ConaxWorkflowManager")]
[assembly: AssemblyDescriptionAttribute("MPS.MPP.Auxiliary.ConaxWorkflowManager")]

